apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.name" . }}-headless
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.postgres.service1.port }}
      targetPort: {{ .Values.postgres.service1.targetPort }}
      protocol: {{ .Values.postgres.service1.protocol }}
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
